PLAYER1=group2
PLAYER2=group4
PLAYER3=group4
PLAYER4=group1

MAP=holes.map

RADIUS=10

L=15
W=20

GUI=false

NROUNDS=500

run:
	java outpost.sim.Outpost $(MAP) $(RADIUS) $(L) $(W) $(GUI) $(PLAYER1) $(PLAYER2) $(PLAYER3) $(PLAYER4) $(NROUNDS)

dumb:
	java outpost.sim.Outpost

compile:
	javac ./outpost/sim/*.java
